---
- name: Remove ffmpeg x264 libx264-dev
  apt:
    name:  "{{ item }}"
    state: absent
  with_items:
    - ffmpeg
    - x264
    - libx264-dev

#- name: Run the equivalent of "apt-get update" as a separate step
#  apt:
#    update_cache: yes

- name: update and install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - libgstreamer0.10-0
    - libgstreamer0.10-dev
    - gstreamer0.10-tools
    - gstreamer0.10-plugins-base
    - libgstreamer-plugins-base0.10-dev
    - libopencv-dev
    - build-essential
    - cmake
    - git
    - libgtk2.0-dev
    - pkg-config
    - python-dev
    - python-numpy
    - libdc1394-22
    - libdc1394-22-dev
    - libjpeg-dev
    - libpng12-dev
    - libtiff5-dev
    - libjasper-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libxine2-dev
    - libgstreamer0.10-dev
    - libgstreamer-plugins-base0.10-dev
    - libv4l-dev
    - libtbb-dev
    - libqt4-dev
    - libfaac-dev
    - libmp3lame-dev
    - libopencore-amrnb-dev
    - libopencore-amrwb-dev
    - libtheora-dev
    - libvorbis-dev
    - libxvidcore-dev
    - x264
    - v4l-utils
    - unzip
    - libconfig++-dev
    - qt5-default
    - gstreamer0.10-plugins-good
    - ffmpeg
    - frei0r-plugins
    - ubuntu-restricted-extras
    - liblapacke-dev

- name: download and unarchive fastflow
  unarchive:
    src: https://github.com/opencv/opencv/archive/3.2.0.zip
    dest: "{{ home_dir }}"
    remote_src: True
  sudo: no

- name: mkdir build
  file: path="{{ opencv_build_dir }}" state=directory
  sudo: no

- name: cmake
  shell: 'cmake -DWITH_XINE=ON -DCMAKE_BUILD_TYPE=RELEASE -DWITH_VTK=ON -DWITH_QT=ON -DWITH_LIBV4L=ON -DBUILD_TIFF=ON -DBUILD_opencv_java=OFF -DWITH_CUDA=OFF -DWITH_FFMPEG=ON -DENABLE_AVX=ON -DWITH_OPENGL=ON -DWITH_OPENCL=ON -DWITH_IPP=OFF -DWITH_TBB=ON -DWITH_EIGEN=ON -DWITH_V4L=ON -DBUILD_TESTS=OFF -DBUILD_PERF_TESTS=OFF -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=/usr/local -DPYTHON3_EXECUTABLE=$(which python3.5) -DPYTHON3_INCLUDE_DIR=$(python3 -c "from distutils.sysconfig import get_python_inc; print(get_python_inc())") -DPYTHON3_PACKAGES_PATH=$(python3 -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())") ..'
  args:
    chdir: "{{ opencv_build_dir }}"
  sudo: no

- name: make clean
  shell: make clean
  args:
    chdir: "{{ opencv_build_dir }}"
  sudo: no

- name: make
  shell: "make -j $(nproc)"
  args:
    chdir: "{{ opencv_build_dir }}"
  sudo: no

- name: ldconfig
  shell: ldconfig
  args:
    chdir: "{{ opencv_build_dir }}"

- name: make install
  shell: make install
  args:
    chdir: "{{ opencv_build_dir }}"

- name: linking opecv library
  shell: sh -c 'echo "/usr/local/lib" > /etc/ld.so.conf.d/opencv.conf'

- name: ln /dev/null /dev/raw1394
  shell: ln /dev/null /dev/raw1394

- name: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/opencv/lib
  shell: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/opencv/lib
  sudo: no